### ISSUE TITLE
Unecessary string parsing for JSON objects

### ISSUE THREAD

**Issue by TjWallas** [TjWallas/dynamic-netsec#9]
https://github.com/TjWallas/dynamic-netsec/blob/1e2fc59a499b9a45ef5d4cc9c0f0da2443178446/democli/key_value_store.py#L57

Why is the above line necessary??

**Comment by xiecancn** [comment]
Consider following code as an example:
`c = consul.Consul()`
`test = {"Address" : "172.16.20.94", "Node" : "node3", "ACLRule" : []}`
`c.kv.put('container/test', str(test))`
`_, data = c.kv.get('container/test')`
`print(data)`

The output is:
`{'Key': 'container/test', 'Value': b"{'Address': '172.16.20.94', 'Node': 'node3', 'ACLRule': []}", 'CreateIndex': 9494, 'ModifyIndex': 15131, 'LockIndex': 0, 'Flags': 0}`

The 'Value' is returned in bytes, not string. That's why the **decode()** is needed. The relevant issue from Consul is [here](https://github.com/cablehead/python-consul/issues/172). 

The other thing is that `{'Address': '172.16.20.94', 'Node': 'node3', 'ACLRule': []}` is not in JSON format since it uses single quote rather than double quote.  Without replacing the single quotes with double quotes will result in Error:
`json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

**Comment by TjWallas** [comment]
@xiecancn Thanks for the clarification. My question then is: Since you are doing all this in python anyways, why not directly deal with the dicts? I think that you only need to deserialize JSON objects when you receive them from some HTTP response, right?
